version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci: "
