repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-yaml
        exclude: "{{cookiecutter.project_name}}/mkdocs.yml"
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: name-tests-test

-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.1
    hooks:
    -   id: check-dependabot
    -   id: check-github-workflows
