repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
        exclude: "{{cookiecutter.project_folder}}"
    -   id: check-yaml
        exclude: "{{cookiecutter.project_folder}}"
    -   id: check-added-large-files
    -   id: debug-statements
        exclude: "{{cookiecutter.project_folder}}"

-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.5
    hooks:
    -   id: check-dependabot
    -   id: check-github-workflows

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
    -   id: ruff # linter
        args: [ --fix ]
        exclude: "{{cookiecutter.project_folder}}"
    -   id: ruff-format
        exclude: "{{cookiecutter.project_folder}}"

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
    -   id: commitizen
