fix = true
line-length = 100
exclude = [
    ".git",
    ".eggs",
    ".mypy_cache",
    ".ruff_cache",
    ".pytest_cache",
    "__pypackages__",
    ".venv",
    "cookiecutter.",
]

[format]
quote-style = "single"

[lint.isort]
force-single-line = true
