[tool.commitizen]
name = "cz_customize"
tag_format = "$version"
version_scheme = "semver"
version_provider = "scm"

[tool.commitizen.customize]
message_template = "{{change_type}}{% if scope != '' %}({{scope}}){% endif %}: {{message}}"
example = "ci(dev): add commitizen to automate commit message build"
schema = "<type>(<scope>): <body>"

[[tool.commitizen.customize.questions]]
type = "list"
name = "change_type"
message = "Select the type of change you are committing"
choices = [
    {value = "feat", name = "feat: A new feature. Correlates with MINOR in SemVer"},
    {value = "fix", name = "fix: A bug fix. Correlates with PATCH in SemVer"},
    {value = "refactor", name = "refactor: A code change that neither fixes a bug nor adds a feature"},
    {value = "docs", name = "docs: Documentation only changes"},
    {value = "perf", name = "perf: A code change that improves performance"},
    {value = "style", name = "style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)"},
    {value = "test", name = "test: Adding missing or correcting existing tests"},
    {value = "build", name = "build: Changes that affect the build system or external dependencies (cookiecutter, pip, docker, etc)"},
    {value = "ci", name = "ci: Changes to CI configuration files and scripts (github actions, pre-commit, make, etc)"},
    {value = "chore", name = "chore: Changes to project configuration (.editorconfig, pyproject.toml, .gitignore, etc)"},
    {value = "revert", name = "revert: Undo changes made in previous commits"},
]

[[tool.commitizen.customize.questions]]
type = "input"
name = "scope"
message = "What is the scope of this change?: (press [enter] to skip)"

[[tool.commitizen.customize.questions]]
type = "input"
name = "message"
message = "Write a short and imperative summary of the code changes: (lower case and no period)\n"
