repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: name-tests-test

-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.5
    hooks:
    -   id: check-dependabot
    -   id: check-github-workflows

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff # linter
        args: [ --fix ]
      - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
