site_name: {{ cookiecutter.project_name }}
theme:
  name: material

copyright: |
  &copy; 2023 <a href="https://github.com/{{cookiecutter.github_username}}"  target="_blank" rel="noopener">{{ cookiecutter.full_name }}</a>
