[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.0.1"
authors = [
    {name = "{{ cookiecutter.full_name }}", email = "{{ cookiecutter.email }}"},
]
requires-python = ">={{ cookiecutter.python_version }}"

[project.optional-dependencies]
dev = [
    "pip-tools",
    "cleanpy",
    "pre-commit",
{%- if cookiecutter.documentation_framework == "MKDocs" %}
    "mkdocs-material",
{%- endif %}
]

[project.urls]
repository = "https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_folder}}"
{%- if cookiecutter.documentation_framework == "MKDocs" %}
documentation = "https://{{cookiecutter.github_username}}.github.io/{{cookiecutter.project_folder}}"
{%- endif %}
