name: Pre-commit autoupdate

on:
  schedule:
    - cron: '0 0 * * 1' # Mondays at 00:00

  # Enable manual execution
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.ref_name }}
          branch: dependency/pre-commit
          commit-message: 'ci(pre-commit): run `pre-commit autoupdate`'
          title: 'ci(dev-deps): bump pre-commit hooks version'
          body: Update versions of tools in pre-commit configs to latest version
          labels: dependencies,pre-commit
